export const OVERVIEW_CAMERA = {
    position: [0, 44, 92],
    target: [0, 0, 0],
};

export const SHAPE_OPTIONS = [
    { key: "sphere", label: "球体" },
    { key: "box", label: "立方体" },
    { key: "octahedron", label: "八面体" },
    { key: "cylinder", label: "圆柱体" },
    { key: "cone", label: "圆锥体" },
    { key: "dodecahedron", label: "十二面体" },
    { key: "icosahedron", label: "二十面体" },
    { key: "capsule", label: "胶囊体" },
    { key: "torusKnot", label: "环面结" },
];

export const UNIQUE_SHAPE_SET = {
    mercury: "box",
    venus: "octahedron",
    earth: "capsule",
    mars: "cone",
    jupiter: "dodecahedron",
    saturn: "cylinder",
    uranus: "icosahedron",
    neptune: "torusKnot",
};

export const SUN_CONFIG = {
    key: "sun",
    label: "太阳",
    radius: 6,
    texture: "sun.jpg",
    rotationSpeed: 0.12,
    materialType: "emissive",
    replaceable: false,
};

export const PLANET_CONFIG = [
    {
        key: "mercury",
        label: "水星",
        radius: 0.4,
        distance: 10,
        orbitSpeed: 0.24,
        rotationSpeed: 0.06,
        texture: "mercury.jpg",
        shininess: 8,
        tilt: 0.03,
    },
    {
        key: "venus",
        label: "金星",
        radius: 0.9,
        distance: 14,
        orbitSpeed: 0.09,
        rotationSpeed: 0.06,
        texture: "venus.jpg",
        shininess: 14,
        tilt: 0.04,
    },
    {
        key: "earth",
        label: "地球",
        radius: 1.0,
        distance: 19,
        orbitSpeed: 0.06,
        rotationSpeed: 0.12,
        texture: "earth.jpg",
        shininess: 24,
        tilt: 0.41,
        moon: {
            key: "moon",
            label: "月球",
            radius: 0.27,
            distance: 2.6,
            orbitSpeed: 0.48,
            rotationSpeed: 0.18,
            texture: "moon.jpg",
            shininess: 4,
        },
    },
    {
        key: "mars",
        label: "火星",
        radius: 0.5,
        distance: 24,
        orbitSpeed: 0.048,
        rotationSpeed: 0.12,
        texture: "mars.jpg",
        shininess: 9,
        tilt: 0.2,
    },
    {
        key: "jupiter",
        label: "木星",
        radius: 2.8,
        distance: 34,
        orbitSpeed: 0.012,
        rotationSpeed: 0.24,
        texture: "jupiter.jpg",
        shininess: 18,
        tilt: 0.05,
    },
    {
        key: "saturn",
        label: "土星",
        radius: 2.3,
        distance: 46,
        orbitSpeed: 0.006,
        rotationSpeed: 0.228,
        texture: "saturn.jpg",
        shininess: 18,
        tilt: 0.47,
        ring: {
            texture: "saturn_ring.png",
            innerScale: 1.4,
            outerScale: 2.4,
            tilt: Math.PI / 2,
        },
    },
    {
        key: "uranus",
        label: "天王星",
        radius: 1.5,
        distance: 56,
        orbitSpeed: 0.003,
        rotationSpeed: 0.18,
        texture: "uranus.jpg",
        shininess: 10,
        tilt: 1.71,
    },
    {
        key: "neptune",
        label: "海王星",
        radius: 1.4,
        distance: 65,
        orbitSpeed: 0.0006,
        rotationSpeed: 0.18,
        texture: "neptune.jpg",
        shininess: 11,
        tilt: 0.5,
    },
];
